name: DSQuest
version: ${project.version}
main: com.dreamstory.quest.DSQuest
api-version: 1.18
depend:
  - DSLibrary
  - DSAbility
  - DSCrafting
  - BetonQuest
commands:
  questtest:
    description: quest
